[package]
name = "nyxhop"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.35.0", default-features = false, features = [
    "accesskit",
    "default_fonts",
    "wgpu",
] }
egui = "0.35.0"
nyx-common = { path = "../../link/nyx-common" }
nyx-proto = { path = "../../link/nyx-proto" }
nyx-rx = { path = "../video/nyx-rx" }
nyx-tx = { path = "../video/nyx-tx" }
